Add turbulence correction mode using stationary positioners
desihub/desimeter pull request #186
Opened 2021-08-21 04:27 UTC by schlafly

This PR adds functionality for performing turbulence correction using stationary positioners to measure the turbulence in the volume of air between the FVC and the focal plane.  The main feature is a new `correct_using_stationary` routine that specifies which positioners are stationary and the locations at which turbulence predictions are desired.

In order to make the turbulence correction faster and more robust, by default this mode does not fit for the covariance matrix in each image, but instead fixes the covariance matrix.  An additonal option scales the covariance matrix by a constant, essentially allowing the expected positions to be specified in different units---for example, in FVC pixels rather than in microns in the focal plane.

Given the expected use in the online system, the module now tries to use the online logger if available.  Otherwise it defaults to the desimeter logger.

2021-08-21 04:28 UTC, schlafly commented
@julienguy, I think this looks fine, but you may object to looking for the DOSLib logger before the desimeter logger.  This is to make life easier for Klaus, but let me know if you prefer another solution.

2021-08-23 21:42 UTC, schlafly commented
Here's an example invocation:
```
cd /global/cfs/cdirs/desi/users/jguy/focalplane/petal1-at-lbl/turbulence/challenge
measured = ascii.read('measured.csv')
expected = ascii.read('expected.csv')
data = turbulence.make_data(expected, measured)
xm, ym = data['x']+data['dx'], data['y']+data['dy']
mstationary = np.random.rand(len(data)) < 0.1
xc, yc = turbulence.correct_using_stationary(xm[mstationary], ym[mstationary], data['x'][mstationary], data['y'][mstationary], xm[~mstationary], ym[~mstationary])
clf() ; quiver(data['x'][~mstationary], data['y'][~mstationary], xc-xm[~mstationary], yc-ym[~mstationary])
```

This is a bit messy since there isn't a command line interface and we don't have expected positions in general for the non-moving positioners, so I go and use the old measured / expected positioners.

2021-08-23 23:02 UTC, julienguy requested changes
One online comment. Except for that it's good for me. I ran the test successfully.

2021-08-24 00:56 UTC, schlafly commented on py/desimeter/turbulence.py
> +        if kw.get('rq', False):
Thanks for the close look.  You're right that that's the intended behavior.  But I think that's what this already does?

kw.get('rq', False) just makes the default False if rq isn't found in the dictionary, but the sign of the test is still equivalent to if kw['rq']: ...  So I think this is fine?

2021-08-24 01:31 UTC, julienguy commented on py/desimeter/turbulence.py
> +        if kw.get('rq', False):
ok, my bad.

2021-08-24 01:32 UTC, merged